name: orientation_app
description: "Daystar University's orientation application"
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.3.1 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.6
  get: ^4.6.6 
  http: ^1.2.2
  lottie: ^3.1.2
  shared_preferences: ^2.3.2
  url_launcher: ^6.3.1
  image_picker: ^1.1.2
  firebase_messaging: ^14.7.10
  firebase_core: ^2.24.2
  flutter_local_notifications: ^17.2.2
  pdf: ^3.11.1
  printing: ^5.13.2
  flutter_native_splash: ^2.4.1
  flutter_launcher_icons: ^0.14.3
  google_fonts: ^6.2.1
  pocketbase: ^0.22.0
  get_it: ^8.0.3
  sliver_tools: ^0.2.12
  logger: ^2.5.0
  json_serializable: ^6.9.5
  build_runner: ^2.4.15
  dartz: ^0.10.1
  cached_network_image: ^3.4.1
  

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0
  

flutter:
  uses-material-design: true
#   fonts:
#   - family:  MyFlutterApp
#     fonts:
#       - asset: fonts/MyFlutterApp.ttf

  assets:
    - assets/icons/
    - assets/images/
    - assets/lotties/

    
